# generated by datamodel-codegen:
#   filename:  schema1.json
#   timestamp: 2022-11-26T14:11:12+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field


class Address(BaseModel):
    number: int = Field(..., title='Number')
    street: str = Field(..., title='Street')
    city: str = Field(..., title='City')


class DateModel(BaseModel):
    id: int = Field(..., title='Id')
    inputDate: date = Field(..., title='Inputdate')
    name: Optional[str] = Field('Hello', title='Name')
    address: Address
